### ISSUE TITLE
setTimeout & setInterval not working

### ISSUE THREAD

**Issue by santicros** [statelyai/xstate-viz#205]
Problem:
**setTimeout** & **setInterval** can't be used on the visualizer right now. It gives the error: "setTimeout is not a function".

Demo: https://stately.ai/viz?id=a52dd233-64c9-4476-a869-cd6b58b10a12#

**Comment by davidkpiano** [comment]
This is because the machines are evaluated in a "sandboxed environment" and those global functions aren't available to it. We should be able to allowlist those functions 🤔

**Comment by Andarist** [comment]
Yeah, we are already doing that with `console.log`. Allowing timers should be just a matter of adding this appropriately to the allowlist
