### ISSUE TITLE
`context` is not initialized (intermittently)

### ISSUE THREAD

**Issue by Enteleform** [statelyai/xstate-viz#266]
Found while troubleshooting [xstate#2643](https://github.com/statelyai/xstate/issues/2643) with [this visualizer](https://stately.ai/viz/da8f1ce9-7d90-4031-962d-2f0188c9dc4b).

> If I'm logged into stately.ai & refresh the page, `selectedItem` is always `undefined`.
> In order to get it to work, I have to make an edit and then save the document.
> This workaround only seems to work intermittently, and sometimes requires several edits.
> Screenshot @ https://i.imgur.com/YmucWRW.png

**Comment by Andarist** [comment]
At first, I've thought that this was something else but later on I've realized that most likely [this PR](https://github.com/statelyai/xstate/pull/2649) should fix this. Maybe let's wait until it lands and then recheck if your problem went away?

**Comment by Enteleform** [comment]
> Maybe let's wait until it lands and then recheck if your problem went away?

Sounds good 👍, just subscribed to the PR.

**Comment by Andarist** [comment]
That PR has been merged and a new version of XState has been released, we only need to bump it here, in the viz. I've done it here: https://github.com/statelyai/xstate-viz/pull/268 so you should even be able to check your code with the preview build that will soon be posted by Vercel in the comment there.

**Comment by Enteleform** [comment]
@Andarist
Checked out the preview build, seems to be working as expected w/ the original example 👍.
