### ISSUE TITLE
Birds eye mode

### ISSUE THREAD

**Issue by a-uz** [statelyai/xstate-viz#272]
This is an early stage feature request.

Right now I'm modeling a machine that has a bunch of compound and parallel states on multiple levels:

![image](https://user-images.githubusercontent.com/6834140/133851007-6ba838a9-a708-4c5a-8690-e64c75bc1cf3.png)

It's still incomplete and very simple, but when I'll come back to it tomorrow to continue it will seem too complicated. So I would like to have a way to view it from the first level of states and only when I click on a particular state, it would reveal it's contents.

If this is something that you think that could be useful, I'd be open for a discussion and help in any way possible, and if not, then feel free to close this issue.

**Comment by davidkpiano** [comment]
I definitely think it's a good idea, and seems to be related to the suggestion of being able to collapse state nodes.
