### ISSUE TITLE
Multiple root events break Viz chart

### ISSUE THREAD

**Issue by cedricradicia** [statelyai/xstate-viz#279]
**Description**
If a multiple root events are created, the Viz don't display chart.

The following code don't work:
`
  {
    on: {
      LOAD: {},
      UPDATE: {},
    },
    states: {
      something: {
      }
    },
  }
`

The following code work as espected:
`
  {
    on: {
      UPDATE: {},
    },
    states: {
      something: {
      }
    },
  }
`

**Expected Result**

The Viz would display two arrow on the top of the main machine box

**Actual Result**

The Viz don't display anything

**Reproduction**

I have create a machine to reproduce it:
https://stately.ai/viz/83677847-53ed-4ba2-87da-4f80b6654cab

**Comment by huan** [comment]
Is there have a workaround for this problem?

I ran into this today and it seems that we can not fix it from the JavaScript side?

**Comment by VanTanev** [comment]
Issue persists.

**Comment by davidkpiano** [comment]
> Issue persists.

Fix coming right up!

**Comment by VanTanev** [comment]
Thank you, David!
