### ISSUE TITLE
Add `vim` mode to the editor

### ISSUE THREAD

**Issue by with-heart** [statelyai/xstate-viz#299]
As a `vim` user, I would like to be able to enable `vim` mode for the editor, so that I can use the keybindings familiar to me to navigate and edit the code. Obviously not a major feature directly related to the visualizer, but it would be a nice quality of life improvement to have available that's common in many online editors.

**Comment by kiyov09** [comment]
👍

**Comment by davidkpiano** [comment]
Can you add this to statelyai.canny.io ? 🙏

**Comment by with-heart** [comment]
@davidkpiano Done! https://statelyai.canny.io/editor/p/add-vim-mode-to-code-editor
