### ISSUE TITLE
Embed Src Address misses https://stately.ai/  

### ISSUE THREAD

**Issue by marcograhl** [statelyai/xstate-viz#306]
**Description**
When I save the Diagram, I can click on share -> embed and the code I can Copy looks like that
<iframe src="/viz/embed/...

**Expected Result**
It works when I use:
<iframe src="https://stately.ai/viz/embed/...

Maybe somebody can check if it they have the same Problem.

**Comment by avaragado** [comment]
Same problem.

**Comment by farskid** [comment]
Thank you for reporting this issue. It's been already fixed in https://github.com/statelyai/xstate-viz/commit/19ec9c0032c4360eddcabbb07cdb2757b5d84ea0#diff-e17609817b7231df8affda1c3a130eab7c32c8902389990682de8ba0b096b442 and soon to be released along https://github.com/statelyai/xstate-viz/pull/290
