### ISSUE TITLE
 when I add import { createUpdater} from "xstate/immer"; to stately Visualizer, I get error, How can I fix it? please

### ISSUE THREAD

**Issue by Avisa-GA** [statelyai/xstate-viz#322]
**Description**

**Expected Result**

**Actual Result**

**Reproduction**

**Additional context**

**Comment by davidkpiano** [comment]
Unfortunately, `xstate/immer` is not available in the visualizer.

Instead, use one of the [templates](https://github.com/statelyai/xstate#templates) and add `@xstate/inspect` to see the machines with the visualizer. You can use `@xstate/immer` in there.

**Comment by Avisa-GA** [comment]
Yes I want to be able to show with visualizer to my team, and some of them are not Software Engineer.
 Thank You.


Sent from Yahoo Mail for iPhone


On Wednesday, November 24, 2021, 6:02 PM, David Khourshid ***@***.***> wrote:




Unfortunately, xstate/immer is not available in the visualizer.

Instead, use one of the templates and add @xstate/inspect to see the machines with the visualizer. You can use @xstate/immer in there.

**Comment by davidkpiano** [comment]
Here is an example that uses the visualizer and XState Immer: https://codesandbox.io/s/xstate-immer-inspect-sgvdo

**Comment by Avisa-GA** [comment]
Thank You 😊 


Sent from Yahoo Mail for iPhone


On Thursday, November 25, 2021, 7:44 AM, David Khourshid ***@***.***> wrote:




Here is an example that uses the visualizer and XState Immer: https://codesandbox.io/s/xstate-immer-inspect-sgvdo
