### ISSUE TITLE
when visualizing, throw Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by WangLarry** [statelyai/xstate-viz#340]
viz:  https://stately.ai/viz/f4d0b7e0-7f6f-445b-9c36-9ab48d565b9c

**Comment by judicaelandria** [comment]
Hi @WangLarry, this happened because you misused the eventless transitions here "always" so it creates infinite loops, if you remove the always it should work.
as the docs say 
> Eventless transitions should be defined either with target, cond + target, cond + actions, or cond + target + actions
