### ISSUE TITLE
Yarn install fails

### ISSUE THREAD

**Issue by donald-richardson-dxd** [statelyai/xstate-viz#355]
**Description**

Yarn install fails to install. No node_modules directory is created so the postinstall fails. Not sure where the actual bug is.

**Expected Result**

Expect the install to work

**Actual Result**

Install doesn't work

**Reproduction**

Not sure what to do here.

**Additional context**
➤ YN0032: │ utf-8-validate@npm:5.0.5: Implicit dependencies on node-gyp are discouraged
➤ YN0002: │ @chakra-ui/accordion@npm:1.3.2 [0bf55] doesn't provide framer-motion (p76a49), requested by @chakra-ui/transition
➤ YN0002: │ @chakra-ui/skeleton@npm:1.1.14 [0bf55] doesn't provide @chakra-ui/theme (pabac2), requested by @chakra-ui/media-query
➤ YN0002: │ @chakra-ui/skeleton@npm:1.1.14 [0bf55] doesn't provide @emotion/react (pab30a), requested by @chakra-ui/system
➤ YN0002: │ @chakra-ui/skeleton@npm:1.1.14 [0bf55] doesn't provide @emotion/styled (pa938d), requested by @chakra-ui/system
➤ YN0002: │ @chakra-ui/switch@npm:1.2.5 [0bf55] doesn't provide framer-motion (p23e33), requested by @chakra-ui/checkbox
➤ YN0002: │ @endemolshinegroup/cosmiconfig-typescript-loader@npm:3.0.2 [d8344] doesn't provide typescript (p6a0d6), requested by ts-node
➤ YN0002: │ styled-jsx@npm:4.0.0 [806ea] doesn't provide @babel/core (pbde35), requested by @babel/plugin-syntax-jsx
➤ YN0002: │ xstate-viz-app@workspace:. doesn't provide @babel/core (p81569), requested by babel-jest
➤ YN0002: │ xstate-viz-app@workspace:. doesn't provide @chakra-ui/system (pe6242), requested by @chakra-ui/icons
➤ YN0060: │ xstate-viz-app@workspace:. provides cypress (p51176) with version 8.0.0, which doesn't satisfy what cypress-real-events requests
➤ YN0002: │ xstate-viz-app@workspace:. doesn't provide ws (p928f6), requested by @xstate/inspect
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 11s 697ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs@npm:17.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yauzl@npm:2.10.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yocto-queue@npm:0.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ typescript@npm:4.3.5 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 1m 3s
➤ YN0000: ┌ Link step
➤ YN0007: │ bufferutil@npm:4.0.3 must be built because it never did before or the last one failed
➤ YN0007: │ utf-8-validate@npm:5.0.5 must be built because it never did before or the last one failed
➤ YN0007: │ cypress@npm:8.0.0 must be built because it never did before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.9.0 must be built because it never did before or the last one failed
➤ YN0007: │ xstate-viz-app@workspace:. must be built because it never did before or the last one failed
➤ YN0009: │ xstate-viz-app@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /private/tmp/xfs-1b11a7d7/build.log)
➤ YN0009: │ xstate-viz-app@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /private/tmp/xfs-1b11a7d7/build.log)

Node 14.18.3
Yarn 2.4.3
MacOS Catalina 10.15

**Comment by donald-richardson-dxd** [comment]
If I do an `npm install` it appears to work but then when running `npm run start` I get the following broken look site: 
<img width="1680" alt="Screen Shot 2022-04-03 at 9 56 58 PM" src="https://user-images.githubusercontent.com/67066256/161461706-bf2b9db0-c794-420a-8ad1-7bbc6016e640.png">

**Comment by donald-richardson-dxd** [comment]
What I'm actually trying to do is to get a local version of the inspector: https://statecharts.io/inspect

**Comment by Andarist** [comment]
As to Yarn - it looks like you are using Yarn 2/3 there but we are using Yarn Classic (v1) here.

**Comment by donald-richardson-dxd** [comment]
Would be good to add that to the README.

**Comment by donald-richardson-dxd** [comment]
You can close this ticket, I'll start a new ticket with the other issue.
