### ISSUE TITLE
Local inspect tool

### ISSUE THREAD

**Issue by donald-richardson-dxd** [statelyai/xstate-viz#356]
This may end up being a feature request instead of a bug, but is there an open source version of the statecharts.io/inspect tool? 

Alternatively, when using https://statecharts.io/inspect?server=localhost:8888 the server opens the websocket server using ws instead of wss leading to issues with mixed content. Is there a way to specify wss?

**Comment by donald-richardson-dxd** [comment]
[blocked] The page at https://statecharts.io/inspect?server=localhost:8888 was not allowed to run insecure content from ws://localhost:8888/.

**Comment by Andarist** [comment]
> This may end up being a feature request instead of a bug, but is there an open source version of the statecharts.io/inspect tool?

This tool is being discontinued in favor of the visualizer contained in this repo.

**Comment by Andarist** [comment]
Since we've landed [this PR](https://github.com/statelyai/xstate-viz/pull/293) I assume that this issue here got fixed by it. If not - please forgive me for closing this prematurely and please let me know how the situation could be further improved.
