### ISSUE TITLE
npm install fails with dependencies errors

### ISSUE THREAD

**Issue by mjauernig** [statelyai/xstate-viz#364]
yarn install fails with

**Actual Result**
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @chakra-ui/icons@1.0.13" has unmet peer dependency "@chakra-ui/system@>=1.0.0".
warning "@chakra-ui/icons > @chakra-ui/icon@1.1.9" has unmet peer dependency "@chakra-ui/system@>=1.0.0".
warning "@emotion/styled > @emotion/babel-plugin@11.3.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "@emotion/styled > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.12.13" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @xstate/inspect@0.4.1" has unmet peer dependency "ws@^7.3.1".
warning "next > styled-jsx > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-class-properties@7.12.13" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-object-rest-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > babel-jest@27.0.6" has unmet peer dependency "@babel/core@^7.8.0".
warning "babel-jest > babel-preset-jest@27.0.6" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax@1.0.1" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-async-generators@7.8.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-bigint@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-import-meta@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-json-strings@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-logical-assignment-operators@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-nullish-coalescing-operator@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-numeric-separator@7.10.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-optional-catch-binding@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-optional-chaining@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > babel-preset-current-node-syntax > @babel/plugin-syntax-top-level-await@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > cypress-real-events@1.5.0" has incorrect peer dependency "cypress@^4.x || ^5.x || ^6.x || ^7.x".
[4/4] Building fresh packages...
$ patch-package && mkdir -p public/monaco-editor && cp -r node_modules/monaco-editor public
patch-package 6.4.7
Applying patches...
No patch files found
Syntaxfehler.
error Command failed with exit code 1.

--------------------------------

npm install fails with dependencies errors

**Actual Result**
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @chakra-ui/system@2.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@">=16.8.6" from @chakra-ui/accordion@1.3.2
npm ERR!   node_modules/@chakra-ui/accordion
npm ERR!     @chakra-ui/accordion@"1.3.2" from @chakra-ui/react@1.6.3
npm ERR!     node_modules/@chakra-ui/react
npm ERR!       @chakra-ui/react@"^1.6.3" from the root project
npm ERR!   79 more (@chakra-ui/alert, @chakra-ui/avatar, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=18" from @chakra-ui/system@2.1.0
npm ERR! node_modules/@chakra-ui/system
npm ERR!   peer @chakra-ui/system@">=1.0.0" from @chakra-ui/accordion@1.3.2
npm ERR!   node_modules/@chakra-ui/accordion
npm ERR!     @chakra-ui/accordion@"1.3.2" from @chakra-ui/react@1.6.3
npm ERR!     node_modules/@chakra-ui/react
npm ERR!       @chakra-ui/react@"^1.6.3" from the root project
npm ERR!   peer @chakra-ui/system@">=1.0.0" from @chakra-ui/alert@1.2.5
npm ERR!   node_modules/@chakra-ui/alert
npm ERR!     @chakra-ui/alert@"1.2.5" from @chakra-ui/react@1.6.3
npm ERR!     node_modules/@chakra-ui/react
npm ERR!       @chakra-ui/react@"^1.6.3" from the root project
npm ERR!     1 more (@chakra-ui/toast)
npm ERR!   35 more (@chakra-ui/avatar, @chakra-ui/breadcrumb, ...)
npm ERR!
npm ERR! Conflicting peer dependency: react@18.1.0
npm ERR! node_modules/react
npm ERR!   peer react@">=18" from @chakra-ui/system@2.1.0
npm ERR!   node_modules/@chakra-ui/system
npm ERR!     peer @chakra-ui/system@">=1.0.0" from @chakra-ui/accordion@1.3.2
npm ERR!     node_modules/@chakra-ui/accordion
npm ERR!       @chakra-ui/accordion@"1.3.2" from @chakra-ui/react@1.6.3
npm ERR!       node_modules/@chakra-ui/react
npm ERR!         @chakra-ui/react@"^1.6.3" from the root project
npm ERR!     peer @chakra-ui/system@">=1.0.0" from @chakra-ui/alert@1.2.5
npm ERR!     node_modules/@chakra-ui/alert
npm ERR!       @chakra-ui/alert@"1.2.5" from @chakra-ui/react@1.6.3
npm ERR!       node_modules/@chakra-ui/react
npm ERR!         @chakra-ui/react@"^1.6.3" from the root project
npm ERR!       1 more (@chakra-ui/toast)
npm ERR!     35 more (@chakra-ui/avatar, @chakra-ui/breadcrumb, ...)

**Visualizer not working**
In both cases the editor is not working. Stuck on *Preparing the Editor*
![grafik](https://user-images.githubusercontent.com/7187699/170714707-1702a615-69c6-4d49-9ce2-a28250ae0a7a.png)

**Reproduction**

* Clone this GitHub repo
* Run yarn install or npm install

**Comment by mattpocock** [comment]
Try removing patch-package from the postinstall?

**Comment by mjauernig** [comment]
Hi, 

with patch-package removed, it works. 

Thanks.
