### ISSUE TITLE
Visualizer breaks with multiple events defined in one state

### ISSUE THREAD

**Issue by thinkawitch** [statelyai/xstate-viz#385]
**Description**

Visualizer breaks when multiple events defined in state in some cases. One event works, 2 and more break it.

**Expected Result**

Machine works, visualizer should draw the scheme.

**Actual Result**

Machine works good in app, but not in visualizer - it breaks.

**Reproduction**

https://stately.ai/viz/b47d9101-e8aa-4527-b8e9-6f92b434a5e0

**Additional context**

See 
```
on: {
    ERROR: 'setupFailed',
    //READY: 'setupSuccess', // parser breaks on second event, comment line and it works
}
```

Error in parser: TypeError: Cannot read properties of undefined (reading 'c')

**Comment by davidkpiano** [comment]
This is an issue with ELK. We will soon be using our own layout generation algorithm instead that should fix this.
