### ISSUE TITLE
Stately Visualizer says "Services from a separate process are currently being inspected"

### ISSUE THREAD

**Issue by priyath** [statelyai/xstate-viz#398]
**Description**
I am not sure if this is a bug or if it is expected behavior. 

When I access the Stately visualiser via https://stately.ai/viz?inspect, it shows a message saying "Services from a separate process are currently being inspected". However everything works as expected when accessing via https://stately.ai/vz.

**Expected Result**
Editable visualiser when accessing https://stately.ai/viz?inspect or better understanding of the displayed message.

**Actual Result**
Visualiser shows "Services from a separate process are currently being inspected"

**Reproduction**
Access https://stately.ai/viz?inspect and observe editor.

**Additional context**
This behavior was originally seen in an xstate addon for storybook (https://github.com/SimeonC/storybook-xstate-addon), where the embedded visualiser shows the above error.  The addon seem to internally use the `https://stately.ai/viz?inspect` to load the visualiser.

**Comment by davidkpiano** [comment]
This is working as expected; the `stately.ai/viz?inspect` URL is only for inspected machines; not for normal visualization.
