### ISSUE TITLE
Question about xstate statenode layout calculation

### ISSUE THREAD

**Issue by Md-Aashiqq** [statelyai/xstate-viz#399]
Hello Everyone,

I hope you are doing well. I have been using your open-source project and have a question about how the statenode layout is calculated in xstate.

I noticed that the code in the editor changed into a stateNode with the help of the praseMachine function but I don't know the layout of that node calculated,  and I'm not quite sure how to proceed. Could you give me some guidance on this?

I appreciate the work you have put into this project and any help you could offer would be greatly appreciated. Thank you in advance for your time and expertise.

Best regards,
Mohammed Ashick

**Comment by davidkpiano** [comment]
Hey Mohammed, what do you mean by the node layout? The position of the node?

**Comment by Md-Aashiqq** [comment]
yeah, that is correct, how the positions of edges and nodes calculate, after the prase the code into StateNode.

**Comment by davidkpiano** [comment]
> yeah, that is correct, how the positions of edges and nodes calculate, after the prase the code into StateNode.

We use ELK (https://www.eclipse.org/elk/) for this.
