### ISSUE TITLE
How do I use the visualizer to go from state to state without actions involved?

### ISSUE THREAD

**Issue by suesther** [statelyai/xstate-viz#416]
Hi, I want the visualizer to show a state going to another state with a simple arrow without an action in between them? What would be the syntax to make this happen? 
Thanks!!

**Comment by laurakalbag** [comment]
> Hi, I want the visualizer to show a state going to another state with a simple arrow without an action in between them? What would be the syntax to make this happen?
> Thanks!!

Hi @suesther. If you want your machine to always transition from one state to another without an event, you can use an [eventless (always) transition](https://stately.ai/docs/xstate/transitions-and-choices/always).
